title: 我的Awesome博客
email: zyh12327789@163.com
description: >-
  欢迎来到我的个人博客，我在这里分享我的想法和经验。
baseurl: ""
url: "https://uuuiiinnnmmm.github.io"
github_username:  uuuiiinnnmmm

# Excerpts
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
minima:
  skin: dark
header_pages:
  - about.markdown
  - research.md
  - notes.md
